[package]
name = "graph-motif"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap={version="4",features=["derive"]}
csv="1"
smallvec="1"
int-enum="0.5"
